import type { Flight } from './mock';  // Importing the Flight type for type safety.

export const flights: Flight[] = [
    {
        from: "Istanbul",
        to: "New York",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "JFK",
        departureTime: "09:00",
        arrivalTime: "15:30",
        duration: "10h 30m",
        price: 500,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "London",
        airline: "British Airways",
        departureAirportCode: "IST",
        arrivalAirportCode: "LHR",
        departureTime: "10:15",
        arrivalTime: "13:30",
        duration: "4h 15m",
        price: 300,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Paris",
        airline: "Air France",
        departureAirportCode: "IST",
        arrivalAirportCode: "CDG",
        departureTime: "11:45",
        arrivalTime: "14:30",
        duration: "3h 45m",
        price: 250,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "IST",
        arrivalAirportCode: "DXB",
        departureTime: "12:30",
        arrivalTime: "16:45",
        duration: "4h 15m",
        price: 350,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Sydney",
        airline: "Qantas",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "13:15",
        arrivalTime: "05:30",
        duration: "17h 15m",
        price: 800,
        departureDate: "29-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Istanbul",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "IST",
        arrivalAirportCode: "YYZ",
        departureTime: "14:00",
        arrivalTime: "19:45",
        duration: "10h 45m",
        price: 400,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Berlin",
        airline: "Lufthansa",
        departureAirportCode: "IST",
        arrivalAirportCode: "TXL",
        departureTime: "15:30",
        arrivalTime: "18:15",
        duration: "2h 45m",
        price: 220,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Mumbai",
        airline: "Air India",
        departureAirportCode: "IST",
        arrivalAirportCode: "BOM",
        departureTime: "16:45",
        arrivalTime: "21:30",
        duration: "5h 45m",
        price: 320,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Los Angeles",
        airline: "American Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "LAX",
        departureTime: "17:15",
        arrivalTime: "22:00",
        duration: "11h 45m",
        price: 550,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Rome",
        airline: "Alitalia",
        departureAirportCode: "IST",
        arrivalAirportCode: "FCO",
        departureTime: "18:30",
        arrivalTime: "21:15",
        duration: "2h 45m",
        price: 280,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "IST",
        arrivalAirportCode: "HKG",
        departureTime: "19:45",
        arrivalTime: "11:00",
        duration: "8h 15m",
        price: 600,
        departureDate: "29-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Istanbul",
        to: "Madrid",
        airline: "Iberia",
        departureAirportCode: "IST",
        arrivalAirportCode: "MAD",
        departureTime: "20:15",
        arrivalTime: "23:30",
        duration: "3h 15m",
        price: 260,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "New York",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "JFK",
        departureTime: "10:00",
        arrivalTime: "16:30",
        duration: "11h 30m",
        price: 700,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "London",
        airline: "British Airways",
        departureAirportCode: "IST",
        arrivalAirportCode: "LHR",
        departureTime: "09:15",
        arrivalTime: "12:30",
        duration: "4h 15m",
        price: 300,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Paris",
        airline: "Air France",
        departureAirportCode: "IST",
        arrivalAirportCode: "CDG",
        departureTime: "11:45",
        arrivalTime: "15:00",
        duration: "3h 15m",
        price: 250,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Tokyo",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "NRT",
        departureTime: "12:30",
        arrivalTime: "19:45",
        duration: "11h 15m",
        price: 800,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "IST",
        arrivalAirportCode: "DXB",
        departureTime: "14:00",
        arrivalTime: "17:30",
        duration: "4h 30m",
        price: 350,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Sydney",
        airline: "Qantas",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "16:15",
        arrivalTime: "08:00",
        duration: "15h 45m",
        price: 1100,
        departureDate: "29-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Istanbul",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "IST",
        arrivalAirportCode: "YYZ",
        departureTime: "09:30",
        arrivalTime: "15:45",
        duration: "10h 15m",
        price: 600,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Berlin",
        airline: "Lufthansa",
        departureAirportCode: "IST",
        arrivalAirportCode: "TXL",
        departureTime: "14:45",
        arrivalTime: "17:00",
        duration: "3h 15m",
        price: 270,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Mumbai",
        airline: "Air India",
        departureAirportCode: "IST",
        arrivalAirportCode: "BOM",
        departureTime: "15:30",
        arrivalTime: "19:45",
        duration: "5h 15m",
        price: 320,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Los Angeles",
        airline: "Delta Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "LAX",
        departureTime: "11:00",
        arrivalTime: "18:30",
        duration: "13h 30m",
        price: 850,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Rome",
        airline: "Alitalia",
        departureAirportCode: "IST",
        arrivalAirportCode: "FCO",
        departureTime: "13:45",
        arrivalTime: "16:00",
        duration: "3h 15m",
        price: 250,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "IST",
        arrivalAirportCode: "HKG",
        departureTime: "12:15",
        arrivalTime: "19:30",
        duration: "11h 15m",
        price: 750,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Madrid",
        airline: "Iberia",
        departureAirportCode: "IST",
        arrivalAirportCode: "MAD",
        departureTime: "08:00",
        arrivalTime: "11:15",
        duration: "3h 15m",
        price: 240,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "New York",
        airline: "Delta Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "JFK",
        departureTime: "11:30",
        arrivalTime: "17:00",
        duration: "10h 30m",
        price: 680,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "London",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "LHR",
        departureTime: "08:45",
        arrivalTime: "12:00",
        duration: "3h 15m",
        price: 320,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Paris",
        airline: "Air France",
        departureAirportCode: "IST",
        arrivalAirportCode: "CDG",
        departureTime: "12:15",
        arrivalTime: "15:30",
        duration: "3h 15m",
        price: 260,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Tokyo",
        airline: "Japan Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "NRT",
        departureTime: "09:30",
        arrivalTime: "16:45",
        duration: "11h 15m",
        price: 780,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "IST",
        arrivalAirportCode: "DXB",
        departureTime: "14:45",
        arrivalTime: "18:15",
        duration: "4h 30m",
        price: 360,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Sydney",
        airline: "Qantas",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "16:30",
        arrivalTime: "08:15",
        duration: "15h 45m",
        price: 1150,
        departureDate: "29-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Istanbul",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "IST",
        arrivalAirportCode: "YYZ",
        departureTime: "09:45",
        arrivalTime: "16:00",
        duration: "10h 15m",
        price: 620,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Berlin",
        airline: "Lufthansa",
        departureAirportCode: "IST",
        arrivalAirportCode: "TXL",
        departureTime: "15:00",
        arrivalTime: "17:15",
        duration: "3h 15m",
        price: 280,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Mumbai",
        airline: "Air India",
        departureAirportCode: "IST",
        arrivalAirportCode: "BOM",
        departureTime: "17:00",
        arrivalTime: "21:15",
        duration: "5h 15m",
        price: 330,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Los Angeles",
        airline: "American Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "LAX",
        departureTime: "10:30",
        arrivalTime: "18:00",
        duration: "13h 30m",
        price: 860,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Rome",
        airline: "Alitalia",
        departureAirportCode: "IST",
        arrivalAirportCode: "FCO",
        departureTime: "12:45",
        arrivalTime: "15:00",
        duration: "3h 15m",
        price: 255,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "IST",
        arrivalAirportCode: "HKG",
        departureTime: "11:15",
        arrivalTime: "18:30",
        duration: "11h 15m",
        price: 760,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Madrid",
        airline: "Iberia",
        departureAirportCode: "IST",
        arrivalAirportCode: "MAD",
        departureTime: "09:00",
        arrivalTime: "12:15",
        duration: "3h 15m",
        price: 245,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "New York",
        airline: "American Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "JFK",
        departureTime: "13:30",
        arrivalTime: "19:00",
        duration: "10h 30m",
        price: 690,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "London",
        airline: "British Airways",
        departureAirportCode: "IST",
        arrivalAirportCode: "LHR",
        departureTime: "10:45",
        arrivalTime: "14:00",
        duration: "3h 15m",
        price: 330,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Paris",
        airline: "Air France",
        departureAirportCode: "IST",
        arrivalAirportCode: "CDG",
        departureTime: "14:15",
        arrivalTime: "17:30",
        duration: "3h 15m",
        price: 270,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Tokyo",
        airline: "Japan Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "NRT",
        departureTime: "11:30",
        arrivalTime: "18:45",
        duration: "11h 15m",
        price: 790,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "IST",
        arrivalAirportCode: "DXB",
        departureTime: "15:45",
        arrivalTime: "19:15",
        duration: "4h 30m",
        price: 370,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Sydney",
        airline: "Qantas",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "17:30",
        arrivalTime: "09:15",
        duration: "15h 45m",
        price: 1200,
        departureDate: "29-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Istanbul",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "IST",
        arrivalAirportCode: "YYZ",
        departureTime: "10:00",
        arrivalTime: "16:15",
        duration: "10h 15m",
        price: 630,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Berlin",
        airline: "Lufthansa",
        departureAirportCode: "IST",
        arrivalAirportCode: "TXL",
        departureTime: "16:15",
        arrivalTime: "18:30",
        duration: "3h 15m",
        price: 290,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Mumbai",
        airline: "Air India",
        departureAirportCode: "IST",
        arrivalAirportCode: "BOM",
        departureTime: "18:00",
        arrivalTime: "22:15",
        duration: "5h 15m",
        price: 340,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Los Angeles",
        airline: "Delta Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "LAX",
        departureTime: "12:30",
        arrivalTime: "20:00",
        duration: "13h 30m",
        price: 870,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Rome",
        airline: "Alitalia",
        departureAirportCode: "IST",
        arrivalAirportCode: "FCO",
        departureTime: "13:45",
        arrivalTime: "17:00",
        duration: "3h 15m",
        price: 265,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "IST",
        arrivalAirportCode: "HKG",
        departureTime: "12:30",
        arrivalTime: "19:45",
        duration: "11h 15m",
        price: 770,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Madrid",
        airline: "Iberia",
        departureAirportCode: "IST",
        arrivalAirportCode: "MAD",
        departureTime: "10:15",
        arrivalTime: "13:30",
        duration: "3h 15m",
        price: 250,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "New York",
        airline: "American Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "JFK",
        departureTime: "14:30",
        arrivalTime: "20:00",
        duration: "10h 30m",
        price: 700,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "London",
        airline: "British Airways",
        departureAirportCode: "IST",
        arrivalAirportCode: "LHR",
        departureTime: "11:45",
        arrivalTime: "15:00",
        duration: "3h 15m",
        price: 350,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Paris",
        airline: "Air France",
        departureAirportCode: "IST",
        arrivalAirportCode: "CDG",
        departureTime: "15:15",
        arrivalTime: "18:30",
        duration: "3h 15m",
        price: 280,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Tokyo",
        airline: "Japan Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "NRT",
        departureTime: "12:30",
        arrivalTime: "19:45",
        duration: "11h 15m",
        price: 820,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "IST",
        arrivalAirportCode: "DXB",
        departureTime: "16:00",
        arrivalTime: "19:30",
        duration: "4h 30m",
        price: 380,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Sydney",
        airline: "Qantas",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "18:15",
        arrivalTime: "09:00",
        duration: "15h 45m",
        price: 1250,
        departureDate: "29-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Istanbul",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "IST",
        arrivalAirportCode: "YYZ",
        departureTime: "11:15",
        arrivalTime: "17:30",
        duration: "10h 15m",
        price: 650,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Berlin",
        airline: "Lufthansa",
        departureAirportCode: "IST",
        arrivalAirportCode: "TXL",
        departureTime: "17:15",
        arrivalTime: "19:30",
        duration: "3h 15m",
        price: 300,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Mumbai",
        airline: "Air India",
        departureAirportCode: "IST",
        arrivalAirportCode: "BOM",
        departureTime: "19:00",
        arrivalTime: "23:15",
        duration: "5h 15m",
        price: 360,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Los Angeles",
        airline: "Delta Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "LAX",
        departureTime: "13:00",
        arrivalTime: "20:30",
        duration: "13h 30m",
        price: 890,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Rome",
        airline: "Alitalia",
        departureAirportCode: "IST",
        arrivalAirportCode: "FCO",
        departureTime: "14:15",
        arrivalTime: "17:30",
        duration: "3h 15m",
        price: 275,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "IST",
        arrivalAirportCode: "HKG",
        departureTime: "12:45",
        arrivalTime: "20:00",
        duration: "11h 15m",
        price: 780,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "Istanbul",
        to: "Madrid",
        airline: "Iberia",
        departureAirportCode: "IST",
        arrivalAirportCode: "MAD",
        departureTime: "11:30",
        arrivalTime: "14:45",
        duration: "3h 15m",
        price: 255,
        departureDate: "29-10-2023",
        arrivalDate: "29-10-2023",
    },
    {
        from: "New York",
        to: "Istanbul",
        airline: "Delta Airlines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "IST",
        departureTime: "08:30",
        arrivalTime: "15:45",
        duration: "10h 15m",
        price: 720,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "London",
        to: "Istanbul",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "IST",
        departureTime: "10:45",
        arrivalTime: "17:00",
        duration: "3h 15m",
        price: 360,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Paris",
        to: "Istanbul",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "IST",
        departureTime: "12:15",
        arrivalTime: "18:30",
        duration: "3h 15m",
        price: 290,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Tokyo",
        to: "Istanbul",
        airline: "Japan Airlines",
        departureAirportCode: "NRT",
        arrivalAirportCode: "IST",
        departureTime: "09:30",
        arrivalTime: "16:45",
        duration: "11h 15m",
        price: 840,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Dubai",
        to: "Istanbul",
        airline: "Emirates",
        departureAirportCode: "DXB",
        arrivalAirportCode: "IST",
        departureTime: "14:45",
        arrivalTime: "21:00",
        duration: "4h 15m",
        price: 430,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Sydney",
        to: "Istanbul",
        airline: "Qantas",
        departureAirportCode: "SYD",
        arrivalAirportCode: "IST",
        departureTime: "16:30",
        arrivalTime: "00:15",
        duration: "15h 45m",
        price: 1280,
        departureDate: "30-10-2023",
        arrivalDate: "31-10-2023",
    },
    {
        from: "Toronto",
        to: "Istanbul",
        airline: "Air Canada",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "IST",
        departureTime: "09:45",
        arrivalTime: "16:00",
        duration: "10h 15m",
        price: 670,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Berlin",
        to: "Istanbul",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "IST",
        departureTime: "15:00",
        arrivalTime: "21:15",
        duration: "6h 15m",
        price: 390,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Mumbai",
        to: "Istanbul",
        airline: "Air India",
        departureAirportCode: "BOM",
        arrivalAirportCode: "IST",
        departureTime: "17:00",
        arrivalTime: "23:15",
        duration: "6h 15m",
        price: 360,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Los Angeles",
        to: "Istanbul",
        airline: "Delta Airlines",
        departureAirportCode: "LAX",
        arrivalAirportCode: "IST",
        departureTime: "10:30",
        arrivalTime: "17:45",
        duration: "12h 15m",
        price: 880,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Rome",
        to: "Istanbul",
        airline: "Alitalia",
        departureAirportCode: "FCO",
        arrivalAirportCode: "IST",
        departureTime: "12:45",
        arrivalTime: "19:00",
        duration: "6h 15m",
        price: 350,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Hong Kong",
        to: "Istanbul",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "IST",
        departureTime: "11:15",
        arrivalTime: "17:30",
        duration: "8h 15m",
        price: 590,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Madrid",
        to: "Istanbul",
        airline: "Iberia",
        departureAirportCode: "MAD",
        arrivalAirportCode: "IST",
        departureTime: "09:00",
        arrivalTime: "15:15",
        duration: "6h 15m",
        price: 320,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "New York",
        to: "Istanbul",
        airline: "American Airlines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "IST",
        departureTime: "09:30",
        arrivalTime: "16:45",
        duration: "10h 15m",
        price: 730,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "London",
        to: "Istanbul",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "IST",
        departureTime: "11:45",
        arrivalTime: "18:00",
        duration: "3h 15m",
        price: 370,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Paris",
        to: "Istanbul",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "IST",
        departureTime: "13:15",
        arrivalTime: "19:30",
        duration: "3h 15m",
        price: 300,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Tokyo",
        to: "Istanbul",
        airline: "Japan Airlines",
        departureAirportCode: "NRT",
        arrivalAirportCode: "IST",
        departureTime: "10:30",
        arrivalTime: "17:45",
        duration: "11h 15m",
        price: 850,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Dubai",
        to: "Istanbul",
        airline: "Emirates",
        departureAirportCode: "DXB",
        arrivalAirportCode: "IST",
        departureTime: "15:45",
        arrivalTime: "22:00",
        duration: "4h 15m",
        price: 440,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Sydney",
        to: "Istanbul",
        airline: "Qantas",
        departureAirportCode: "SYD",
        arrivalAirportCode: "IST",
        departureTime: "17:30",
        arrivalTime: "01:15",
        duration: "15h 45m",
        price: 1320,
        departureDate: "30-10-2023",
        arrivalDate: "31-10-2023",
    },
    {
        from: "Toronto",
        to: "Istanbul",
        airline: "Air Canada",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "IST",
        departureTime: "11:45",
        arrivalTime: "18:00",
        duration: "10h 15m",
        price: 690,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Berlin",
        to: "Istanbul",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "IST",
        departureTime: "16:15",
        arrivalTime: "22:30",
        duration: "6h 15m",
        price: 400,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Mumbai",
        to: "Istanbul",
        airline: "Air India",
        departureAirportCode: "BOM",
        arrivalAirportCode: "IST",
        departureTime: "18:00",
        arrivalTime: "00:15",
        duration: "6h 15m",
        price: 370,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Los Angeles",
        to: "Istanbul",
        airline: "Delta Airlines",
        departureAirportCode: "LAX",
        arrivalAirportCode: "IST",
        departureTime: "11:30",
        arrivalTime: "17:45",
        duration: "12h 15m",
        price: 890,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Rome",
        to: "Istanbul",
        airline: "Alitalia",
        departureAirportCode: "FCO",
        arrivalAirportCode: "IST",
        departureTime: "13:45",
        arrivalTime: "20:00",
        duration: "6h 15m",
        price: 360,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Hong Kong",
        to: "Istanbul",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "IST",
        departureTime: "10:15",
        arrivalTime: "16:30",
        duration: "8h 15m",
        price: 610,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Madrid",
        to: "Istanbul",
        airline: "Iberia",
        departureAirportCode: "MAD",
        arrivalAirportCode: "IST",
        departureTime: "08:30",
        arrivalTime: "14:45",
        duration: "6h 15m",
        price: 340,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "New York",
        to: "Istanbul",
        airline: "American Airlines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "IST",
        departureTime: "14:30",
        arrivalTime: "21:45",
        duration: "10h 15m",
        price: 740,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "London",
        to: "Istanbul",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "IST",
        departureTime: "13:45",
        arrivalTime: "20:00",
        duration: "3h 15m",
        price: 380,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Paris",
        to: "Istanbul",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "IST",
        departureTime: "15:15",
        arrivalTime: "21:30",
        duration: "3h 15m",
        price: 310,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Tokyo",
        to: "Istanbul",
        airline: "Japan Airlines",
        departureAirportCode: "NRT",
        arrivalAirportCode: "IST",
        departureTime: "12:30",
        arrivalTime: "19:45",
        duration: "11h 15m",
        price: 860,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Dubai",
        to: "Istanbul",
        airline: "Emirates",
        departureAirportCode: "DXB",
        arrivalAirportCode: "IST",
        departureTime: "16:45",
        arrivalTime: "23:00",
        duration: "4h 15m",
        price: 450,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Sydney",
        to: "Istanbul",
        airline: "Qantas",
        departureAirportCode: "SYD",
        arrivalAirportCode: "IST",
        departureTime: "18:30",
        arrivalTime: "02:15",
        duration: "15h 45m",
        price: 1360,
        departureDate: "30-10-2023",
        arrivalDate: "31-10-2023",
    },
    {
        from: "Toronto",
        to: "Istanbul",
        airline: "Air Canada",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "IST",
        departureTime: "13:45",
        arrivalTime: "20:00",
        duration: "10h 15m",
        price: 710,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Berlin",
        to: "Istanbul",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "IST",
        departureTime: "18:00",
        arrivalTime: "00:15",
        duration: "6h 15m",
        price: 410,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Mumbai",
        to: "Istanbul",
        airline: "Air India",
        departureAirportCode: "BOM",
        arrivalAirportCode: "IST",
        departureTime: "19:45",
        arrivalTime: "02:00",
        duration: "6h 15m",
        price: 380,
        departureDate: "30-10-2023",
        arrivalDate: "31-10-2023",
    },
    {
        from: "Los Angeles",
        to: "Istanbul",
        airline: "Delta Airlines",
        departureAirportCode: "LAX",
        arrivalAirportCode: "IST",
        departureTime: "15:30",
        arrivalTime: "21:45",
        duration: "12h 15m",
        price: 900,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Rome",
        to: "Istanbul",
        airline: "Alitalia",
        departureAirportCode: "FCO",
        arrivalAirportCode: "IST",
        departureTime: "16:15",
        arrivalTime: "22:30",
        duration: "6h 15m",
        price: 370,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Hong Kong",
        to: "Istanbul",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "IST",
        departureTime: "14:45",
        arrivalTime: "21:00",
        duration: "8h 15m",
        price: 620,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Madrid",
        to: "Istanbul",
        airline: "Iberia",
        departureAirportCode: "MAD",
        arrivalAirportCode: "IST",
        departureTime: "12:30",
        arrivalTime: "18:45",
        duration: "6h 15m",
        price: 350,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "New York",
        to: "Istanbul",
        airline: "American Airlines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "IST",
        departureTime: "12:30",
        arrivalTime: "19:45",
        duration: "10h 15m",
        price: 750,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "London",
        to: "Istanbul",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "IST",
        departureTime: "10:45",
        arrivalTime: "17:00",
        duration: "3h 15m",
        price: 390,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Paris",
        to: "Istanbul",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "IST",
        departureTime: "14:15",
        arrivalTime: "20:30",
        duration: "3h 15m",
        price: 320,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Tokyo",
        to: "Istanbul",
        airline: "Japan Airlines",
        departureAirportCode: "NRT",
        arrivalAirportCode: "IST",
        departureTime: "10:00",
        arrivalTime: "17:15",
        duration: "11h 15m",
        price: 870,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Dubai",
        to: "Istanbul",
        airline: "Emirates",
        departureAirportCode: "DXB",
        arrivalAirportCode: "IST",
        departureTime: "16:15",
        arrivalTime: "22:30",
        duration: "4h 15m",
        price: 460,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Sydney",
        to: "Istanbul",
        airline: "Qantas",
        departureAirportCode: "SYD",
        arrivalAirportCode: "IST",
        departureTime: "17:00",
        arrivalTime: "00:45",
        duration: "15h 45m",
        price: 1380,
        departureDate: "30-10-2023",
        arrivalDate: "31-10-2023",
    },
    {
        from: "Toronto",
        to: "Istanbul",
        airline: "Air Canada",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "IST",
        departureTime: "11:30",
        arrivalTime: "17:45",
        duration: "12h 15m",
        price: 720,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Berlin",
        to: "Istanbul",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "IST",
        departureTime: "17:45",
        arrivalTime: "00:00",
        duration: "6h 15m",
        price: 420,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Mumbai",
        to: "Istanbul",
        airline: "Air India",
        departureAirportCode: "BOM",
        arrivalAirportCode: "IST",
        departureTime: "19:30",
        arrivalTime: "01:45",
        duration: "6h 15m",
        price: 390,
        departureDate: "30-10-2023",
        arrivalDate: "31-10-2023",
    },
    {
        from: "Los Angeles",
        to: "Istanbul",
        airline: "Delta Airlines",
        departureAirportCode: "LAX",
        arrivalAirportCode: "IST",
        departureTime: "14:00",
        arrivalTime: "20:15",
        duration: "12h 15m",
        price: 910,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Rome",
        to: "Istanbul",
        airline: "Alitalia",
        departureAirportCode: "FCO",
        arrivalAirportCode: "IST",
        departureTime: "15:15",
        arrivalTime: "21:30",
        duration: "3h 15m",
        price: 330,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Hong Kong",
        to: "Istanbul",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "IST",
        departureTime: "13:30",
        arrivalTime: "19:45",
        duration: "8h 15m",
        price: 630,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },
    {
        from: "Madrid",
        to: "Istanbul",
        airline: "Iberia",
        departureAirportCode: "MAD",
        arrivalAirportCode: "IST",
        departureTime: "11:15",
        arrivalTime: "17:30",
        duration: "6h 15m",
        price: 360,
        departureDate: "30-10-2023",
        arrivalDate: "30-10-2023",
    },

        
    //Global flights:


    {
        from: "London",
        to: "Tokyo",
        airline: "London Airlines",
        departureAirportCode: "LHR",
        arrivalAirportCode: "NRT",
        departureTime: "08:30",
        arrivalTime: "11:45",
        duration: "3h 15m",
        price: 200,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "London",
        to: "Tokyo",
        airline: "Tokyo Air",
        departureAirportCode: "LHR",
        arrivalAirportCode: "NRT",
        departureTime: "11:30",
        arrivalTime: "15:00",
        duration: "3h 30m",
        price: 400,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "London",
        to: "Tokyo",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "NRT",
        departureTime: "20:30",
        arrivalTime: "23:30",
        duration: "3h 0m",
        price: 300,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "Tokyo",
        to: "London",
        airline: "British Airways",
        departureAirportCode: "NRT",
        arrivalAirportCode: "LHR",
        departureTime: "00:30",
        arrivalTime: "03:30",
        duration: "3h 0m",
        price: 300,
        departureDate: "09-09-2023",
        arrivalDate: "09-09-2023",
    },
    {
        from: "Istanbul",
        to: "Sydney",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "10:00",
        arrivalTime: "20:30",
        duration: "15h 30m",
        price: 1050,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Sydney",
        to: "Istanbul",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "10:00",
        arrivalTime: "20:30",
        duration: "15h 30m",
        price: 700,
        departureDate: "17-09-2023",
        arrivalDate: "17-09-2023",
    },
    {
        from: "New York",
        to: "Toronto",
        airline: "Delta Air Lines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "YYZ",
        departureTime: "11:15",
        arrivalTime: "16:45",
        duration: "7h 30m",
        price: 540,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Paris",
        to: "Mumbai",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "BOM",
        departureTime: "11:30",
        arrivalTime: "19:00",
        duration: "8h 30m",
        price: 760,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Sydney",
        to: "Hong Kong",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "HKG",
        departureTime: "12:15",
        arrivalTime: "18:45",
        duration: "9h 30m",
        price: 800,
        departureDate: "17-09-2023",
        arrivalDate: "17-09-2023",
    },
    {
        from: "Berlin",
        to: "Rome",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "FCO",
        departureTime: "13:00",
        arrivalTime: "15:15",
        duration: "2h 15m",
        price: 250,
        departureDate: "17-09-2023",
        arrivalDate: "17-09-2023",
    },
    {
        from: "Los Angeles",
        to: "Istanbul",
        airline: "Turkish Airlines",
        departureAirportCode: "LAX",
        arrivalAirportCode: "IST",
        departureTime: "14:00",
        arrivalTime: "21:30",
        duration: "13h 30m",
        price: 900,
        departureDate: "17-09-2023",
        arrivalDate: "17-09-2023",
    },
    {
        from: "Istanbul",
        to: "Toronto",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "YYZ",
        departureTime: "09:00",
        arrivalTime: "15:30",
        duration: "10h 30m",
        price: 720,
        departureDate: "18-09-2023",
        arrivalDate: "18-09-2023",
    },
    {
        from: "New York",
        to: "Mumbai",
        airline: "Delta Air Lines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "BOM",
        departureTime: "10:15",
        arrivalTime: "17:45",
        duration: "12h 30m",
        price: 870,
        departureDate: "18-09-2023",
        arrivalDate: "18-09-2023",
    },
    {
        from: "Paris",
        to: "Hong Kong",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "HKG",
        departureTime: "11:30",
        arrivalTime: "19:00",
        duration: "11h 30m",
        price: 920,
        departureDate: "18-09-2023",
        arrivalDate: "18-09-2023",
    },
    {
        from: "Sydney",
        to: "Los Angeles",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "LAX",
        departureTime: "12:00",
        arrivalTime: "18:30",
        duration: "13h 30m",
        price: 850,
        departureDate: "18-09-2023",
        arrivalDate: "18-09-2023",
    },
    {
        from: "London",
        to: "Istanbul",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "IST",
        departureTime: "13:15",
        arrivalTime: "19:45",
        duration: "10h 30m",
        price: 760,
        departureDate: "18-09-2023",
        arrivalDate: "18-09-2023",
    },
    {
        from: "Tokyo",
        to: "Mumbai",
        airline: "All Nippon Airways",
        departureAirportCode: "NRT",
        arrivalAirportCode: "BOM",
        departureTime: "14:30",
        arrivalTime: "22:00",
        duration: "8h 30m",
        price: 720,
        departureDate: "18-09-2023",
        arrivalDate: "18-09-2023",
    },
    {
        from: "Dubai",
        to: "Rome",
        airline: "Emirates",
        departureAirportCode: "DXB",
        arrivalAirportCode: "FCO",
        departureTime: "09:30",
        arrivalTime: "13:45",
        duration: "6h 15m",
        price: 550,
        departureDate: "19-09-2023",
        arrivalDate: "19-09-2023",
    },
    {
        from: "Toronto",
        to: "Hong Kong",
        airline: "Air Canada",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "HKG",
        departureTime: "10:45",
        arrivalTime: "17:15",
        duration: "14h 30m",
        price: 990,
        departureDate: "19-09-2023",
        arrivalDate: "19-09-2023",
    },
    {
        from: "Mumbai",
        to: "Sydney",
        airline: "Air India",
        departureAirportCode: "BOM",
        arrivalAirportCode: "SYD",
        departureTime: "11:00",
        arrivalTime: "21:30",
        duration: "15h 30m",
        price: 1100,
        departureDate: "19-09-2023",
        arrivalDate: "19-09-2023",
    },
    {
        from: "Rome",
        to: "Berlin",
        airline: "Lufthansa",
        departureAirportCode: "FCO",
        arrivalAirportCode: "TXL",
        departureTime: "11:45",
        arrivalTime: "17:15",
        duration: "8h 30m",
        price: 720,
        departureDate: "19-09-2023",
        arrivalDate: "19-09-2023",
    },
    {
        from: "Madrid",
        to: "Los Angeles",
        airline: "Iberia",
        departureAirportCode: "MAD",
        arrivalAirportCode: "LAX",
        departureTime: "12:30",
        arrivalTime: "18:00",
        duration: "11h 30m",
        price: 890,
        departureDate: "19-09-2023",
        arrivalDate: "19-09-2023",
    },
    {
        from: "Hong Kong",
        to: "Toronto",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "YYZ",
        departureTime: "13:15",
        arrivalTime: "18:45",
        duration: "15h 30m",
        price: 1050,
        departureDate: "20-09-2023",
        arrivalDate: "20-09-2023",
    },
    {
        from: "Istanbul",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "IST",
        arrivalAirportCode: "DXB",
        departureTime: "13:45",
        arrivalTime: "18:15",
        duration: "5h 30m",
        price: 450,
        departureDate: "20-09-2023",
        arrivalDate: "20-09-2023",
    },
    {
        from: "New York",
        to: "Berlin",
        airline: "Delta Air Lines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "TXL",
        departureTime: "14:00",
        arrivalTime: "20:30",
        duration: "8h 30m",
        price: 780,
        departureDate: "20-09-2023",
        arrivalDate: "20-09-2023",
    },
    {
        from: "Paris",
        to: "Toronto",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "YYZ",
        departureTime: "09:30",
        arrivalTime: "15:00",
        duration: "10h 30m",
        price: 680,
        departureDate: "20-09-2023",
        arrivalDate: "20-09-2023",
    },
    {
        from: "Sydney",
        to: "Istanbul",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "IST",
        departureTime: "10:15",
        arrivalTime: "16:45",
        duration: "12h 30m",
        price: 890,
        departureDate: "21-09-2023",
        arrivalDate: "21-09-2023",
    },
    {
        from: "Los Angeles",
        to: "Mumbai",
        airline: "Air India",
        departureAirportCode: "LAX",
        arrivalAirportCode: "BOM",
        departureTime: "11:30",
        arrivalTime: "18:00",
        duration: "11h 30m",
        price: 810,
        departureDate: "21-09-2023",
        arrivalDate: "21-09-2023",
    },
    {
        from: "Hong Kong",
        to: "Sydney",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "SYD",
        departureTime: "12:45",
        arrivalTime: "19:15",
        duration: "8h 30m",
        price: 690,
        departureDate: "21-09-2023",
        arrivalDate: "21-09-2023",
    },
    {
        from: "Istanbul",
        to: "Berlin",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "TXL",
        departureTime: "13:15",
        arrivalTime: "17:30",
        duration: "3h 15m",
        price: 320,
        departureDate: "21-09-2023",
        arrivalDate: "21-09-2023",
    },
    {
        from: "New York",
        to: "Los Angeles",
        airline: "American Airlines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "LAX",
        departureTime: "14:30",
        arrivalTime: "20:00",
        duration: "6h 30m",
        price: 580,
        departureDate: "21-09-2023",
        arrivalDate: "21-09-2023",
    },
    {
        from: "Paris",
        to: "Rome",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "FCO",
        departureTime: "09:45",
        arrivalTime: "12:00",
        duration: "2h 15m",
        price: 270,
        departureDate: "22-09-2023",
        arrivalDate: "22-09-2023",
    },
    {
        from: "Toronto",
        to: "Istanbul",
        airline: "Turkish Airlines",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "IST",
        departureTime: "10:00",
        arrivalTime: "15:30",
        duration: "10h 30m",
        price: 750,
        departureDate: "22-09-2023",
        arrivalDate: "22-09-2023",
    },
    {
        from: "Mumbai",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "BOM",
        arrivalAirportCode: "HKG",
        departureTime: "11:15",
        arrivalTime: "17:45",
        duration: "7h 30m",
        price: 620,
        departureDate: "22-09-2023",
        arrivalDate: "22-09-2023",
    },
    {
        from: "Rome",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "FCO",
        arrivalAirportCode: "YYZ",
        departureTime: "11:30",
        arrivalTime: "16:45",
        duration: "8h 15m",
        price: 690,
        departureDate: "22-09-2023",
        arrivalDate: "22-09-2023",
    },
    {
        from: "Madrid",
        to: "Mumbai",
        airline: "Iberia",
        departureAirportCode: "MAD",
        arrivalAirportCode: "BOM",
        departureTime: "12:45",
        arrivalTime: "19:15",
        duration: "10h 30m",
        price: 780,
        departureDate: "22-09-2023",
        arrivalDate: "22-09-2023",
    },
    {
        from: "Hong Kong",
        to: "Berlin",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "TXL",
        departureTime: "13:00",
        arrivalTime: "17:15",
        duration: "4h 15m",
        price: 380,
        departureDate: "23-09-2023",
        arrivalDate: "23-09-2023",
    },
    {
        from: "Madrid",
        to: "Istanbul",
        airline: "Iberia",
        departureAirportCode: "MAD",
        arrivalAirportCode: "IST",
        departureTime: "09:15",
        arrivalTime: "13:45",
        duration: "4h 30m",
        price: 400,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "Hong Kong",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "HKG",
        arrivalAirportCode: "YYZ",
        departureTime: "10:30",
        arrivalTime: "17:00",
        duration: "14h 30m",
        price: 900,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "Istanbul",
        to: "Sydney",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "SYD",
        departureTime: "11:00",
        arrivalTime: "21:30",
        duration: "15h 30m",
        price: 1100,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "New York",
        to: "Berlin",
        airline: "Delta Air Lines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "TXL",
        departureTime: "12:15",
        arrivalTime: "18:45",
        duration: "8h 30m",
        price: 720,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "Paris",
        to: "Hong Kong",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "HKG",
        departureTime: "13:00",
        arrivalTime: "19:30",
        duration: "11h 30m",
        price: 900,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "Sydney",
        to: "Los Angeles",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "LAX",
        departureTime: "14:30",
        arrivalTime: "20:00",
        duration: "12h 30m",
        price: 850,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "London",
        to: "Mumbai",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "BOM",
        departureTime: "09:45",
        arrivalTime: "17:15",
        duration: "9h 30m",
        price: 750,
        departureDate: "13-09-2023",
        arrivalDate: "13-09-2023",
    },
    {
        from: "Tokyo",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "NRT",
        arrivalAirportCode: "YYZ",
        departureTime: "10:15",
        arrivalTime: "16:45",
        duration: "14h 30m",
        price: 950,
        departureDate: "13-09-2023",
        arrivalDate: "13-09-2023",
    },
    {
        from: "Dubai",
        to: "Mumbai",
        airline: "Emirates",
        departureAirportCode: "DXB",
        arrivalAirportCode: "BOM",
        departureTime: "11:30",
        arrivalTime: "16:00",
        duration: "3h 30m",
        price: 380,
        departureDate: "13-09-2023",
        arrivalDate: "13-09-2023",
    },
    {
        from: "Toronto",
        to: "Los Angeles",
        airline: "American Airlines",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "LAX",
        departureTime: "12:45",
        arrivalTime: "19:15",
        duration: "7h 30m",
        price: 680,
        departureDate: "13-09-2023",
        arrivalDate: "13-09-2023",
    },
    {
        from: "Mumbai",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "BOM",
        arrivalAirportCode: "HKG",
        departureTime: "13:00",
        arrivalTime: "19:30",
        duration: "8h 30m",
        price: 820,
        departureDate: "13-09-2023",
        arrivalDate: "13-09-2023",
    },
    {
        from: "Rome",
        to: "Istanbul",
        airline: "Turkish Airlines",
        departureAirportCode: "FCO",
        arrivalAirportCode: "IST",
        departureTime: "14:15",
        arrivalTime: "17:30",
        duration: "2h 15m",
        price: 280,
        departureDate: "13-09-2023",
        arrivalDate: "13-09-2023",
    },
    {
        from: "Madrid",
        to: "New York",
        airline: "Delta Air Lines",
        departureAirportCode: "MAD",
        arrivalAirportCode: "JFK",
        departureTime: "09:30",
        arrivalTime: "16:00",
        duration: "8h 30m",
        price: 650,
        departureDate: "14-09-2023",
        arrivalDate: "14-09-2023",
    },
    {
        from: "Hong Kong",
        to: "Rome",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "FCO",
        departureTime: "10:00",
        arrivalTime: "15:30",
        duration: "10h 30m",
        price: 880,
        departureDate: "14-09-2023",
        arrivalDate: "14-09-2023",
    },
    {
        from: "Istanbul",
        to: "Los Angeles",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "LAX",
        departureTime: "11:45",
        arrivalTime: "18:15",
        duration: "13h 30m",
        price: 920,
        departureDate: "14-09-2023",
        arrivalDate: "14-09-2023",
    },
    {
        from: "New York",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "JFK",
        arrivalAirportCode: "HKG",
        departureTime: "12:30",
        arrivalTime: "19:00",
        duration: "15h 30m",
        price: 1050,
        departureDate: "14-09-2023",
        arrivalDate: "14-09-2023",
    },
    {
        from: "Paris",
        to: "Toronto",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "YYZ",
        departureTime: "13:15",
        arrivalTime: "18:45",
        duration: "8h 30m",
        price: 700,
        departureDate: "14-09-2023",
        arrivalDate: "14-09-2023",
    },
    {
        from: "Sydney",
        to: "Dubai",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "DXB",
        departureTime: "09:45",
        arrivalTime: "16:15",
        duration: "13h 30m",
        price: 950,
        departureDate: "15-09-2023",
        arrivalDate: "15-09-2023",
    },
    {
        from: "Berlin",
        to: "Mumbai",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "BOM",
        departureTime: "10:30",
        arrivalTime: "18:00",
        duration: "10h 30m",
        price: 780,
        departureDate: "15-09-2023",
        arrivalDate: "15-09-2023",
    },
    {
        from: "Los Angeles",
        to: "Toronto",
        airline: "American Airlines",
        departureAirportCode: "LAX",
        arrivalAirportCode: "YYZ",
        departureTime: "11:00",
        arrivalTime: "16:30",
        duration: "5h 30m",
        price: 550,
        departureDate: "15-09-2023",
        arrivalDate: "15-09-2023",
    },
    {
        from: "London",
        to: "Hong Kong",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "HKG",
        departureTime: "12:15",
        arrivalTime: "20:00",
        duration: "10h 45m",
        price: 800,
        departureDate: "15-09-2023",
        arrivalDate: "15-09-2023",
    },
    {
        from: "Madrid",
        to: "Paris",
        airline: "Air France",
        departureAirportCode: "MAD",
        arrivalAirportCode: "CDG",
        departureTime: "13:30",
        arrivalTime: "16:45",
        duration: "2h 15m",
        price: 260,
        departureDate: "15-09-2023",
        arrivalDate: "15-09-2023",
    },
    {
        from: "Toronto",
        to: "Hong Kong",
        airline: "Air Canada",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "HKG",
        departureTime: "14:00",
        arrivalTime: "21:30",
        duration: "15h 30m",
        price: 980,
        departureDate: "15-09-2023",
        arrivalDate: "15-09-2023",
    },
    {
        from: "Sydney",
        to: "Istanbul",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "IST",
        departureTime: "09:30",
        arrivalTime: "15:00",
        duration: "12h 30m",
        price: 900,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Berlin",
        to: "Toronto",
        airline: "Air Canada",
        departureAirportCode: "TXL",
        arrivalAirportCode: "YYZ",
        departureTime: "10:45",
        arrivalTime: "18:15",
        duration: "10h 30m",
        price: 760,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Mumbai",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "BOM",
        arrivalAirportCode: "DXB",
        departureTime: "11:00",
        arrivalTime: "16:30",
        duration: "3h 30m",
        price: 420,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Rome",
        to: "Los Angeles",
        airline: "Alitalia",
        departureAirportCode: "FCO",
        arrivalAirportCode: "LAX",
        departureTime: "11:45",
        arrivalTime: "17:15",
        duration: "11h 30m",
        price: 730,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Madrid",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "MAD",
        arrivalAirportCode: "HKG",
        departureTime: "12:30",
        arrivalTime: "19:00",
        duration: "12h 30m",
        price: 880,
        departureDate: "16-09-2023",
        arrivalDate: "16-09-2023",
    },
    {
        from: "Istanbul",
        to: "New York",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "JFK",
        departureTime: "09:00",
        arrivalTime: "15:30",
        duration: "11h 30m",
        price: 600,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "Paris",
        to: "Dubai",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "DXB",
        departureTime: "10:45",
        arrivalTime: "19:15",
        duration: "7h 30m",
        price: 800,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "Sydney",
        to: "Toronto",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "YYZ",
        departureTime: "11:15",
        arrivalTime: "17:45",
        duration: "17h 30m",
        price: 900,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "Berlin",
        to: "Mumbai",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "BOM",
        departureTime: "12:30",
        arrivalTime: "21:00",
        duration: "9h 30m",
        price: 750,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "Los Angeles",
        to: "Rome",
        airline: "American Airlines",
        departureAirportCode: "LAX",
        arrivalAirportCode: "FCO",
        departureTime: "13:45",
        arrivalTime: "20:15",
        duration: "11h 30m",
        price: 700,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "Hong Kong",
        to: "Madrid",
        airline: "Cathay Pacific",
        departureAirportCode: "HKG",
        arrivalAirportCode: "MAD",
        departureTime: "14:15",
        arrivalTime: "22:45",
        duration: "10h 30m",
        price: 850,
        departureDate: "08-09-2023",
        arrivalDate: "08-09-2023",
    },
    {
        from: "New York",
        to: "Istanbul",
        airline: "Delta Air Lines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "IST",
        departureTime: "09:30",
        arrivalTime: "16:00",
        duration: "11h 30m",
        price: 620,
        departureDate: "09-09-2023",
        arrivalDate: "09-09-2023",
    },
    {
        from: "London",
        to: "Paris",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "CDG",
        departureTime: "10:15",
        arrivalTime: "12:30",
        duration: "1h 15m",
        price: 180,
        departureDate: "09-09-2023",
        arrivalDate: "09-09-2023",
    },
    {
        from: "Tokyo",
        to: "Dubai",
        airline: "Emirates",
        departureAirportCode: "NRT",
        arrivalAirportCode: "DXB",
        departureTime: "11:45",
        arrivalTime: "18:15",
        duration: "8h 30m",
        price: 900,
        departureDate: "09-09-2023",
        arrivalDate: "09-09-2023",
    },
    {
        from: "Toronto",
        to: "Berlin",
        airline: "Air Canada",
        departureAirportCode: "YYZ",
        arrivalAirportCode: "TXL",
        departureTime: "12:30",
        arrivalTime: "20:00",
        duration: "8h 30m",
        price: 780,
        departureDate: "09-09-2023",
        arrivalDate: "09-09-2023",
    },
    {
        from: "Mumbai",
        to: "Los Angeles",
        airline: "Air India",
        departureAirportCode: "BOM",
        arrivalAirportCode: "LAX",
        departureTime: "13:15",
        arrivalTime: "20:45",
        duration: "16h 30m",
        price: 950,
        departureDate: "09-09-2023",
        arrivalDate: "09-09-2023",
    },
    {
        from: "Rome",
        to: "Hong Kong",
        airline: "Alitalia",
        departureAirportCode: "FCO",
        arrivalAirportCode: "HKG",
        departureTime: "14:00",
        arrivalTime: "22:30",
        duration: "11h 30m",
        price: 870,
        departureDate: "09-09-2023",
        arrivalDate: "09-09-2023",
    },
    {
        from: "Istanbul",
        to: "Dubai",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "DXB",
        departureTime: "09:30",
        arrivalTime: "14:45",
        duration: "5h 15m",
        price: 450,
        departureDate: "10-09-2023",
        arrivalDate: "10-09-2023",
    },
    {
        from: "New York",
        to: "London",
        airline: "British Airways",
        departureAirportCode: "JFK",
        arrivalAirportCode: "LHR",
        departureTime: "10:00",
        arrivalTime: "14:30",
        duration: "7h 30m",
        price: 550,
        departureDate: "10-09-2023",
        arrivalDate: "10-09-2023",
    },
    {
        from: "Paris",
        to: "Toronto",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "YYZ",
        departureTime: "11:15",
        arrivalTime: "17:45",
        duration: "8h 30m",
        price: 700,
        departureDate: "10-09-2023",
        arrivalDate: "10-09-2023",
    },
    {
        from: "Sydney",
        to: "Mumbai",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "BOM",
        departureTime: "12:30",
        arrivalTime: "20:00",
        duration: "9h 30m",
        price: 800,
        departureDate: "10-09-2023",
        arrivalDate: "10-09-2023",
    },
    {
        from: "Berlin",
        to: "Rome",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "FCO",
        departureTime: "13:45",
        arrivalTime: "16:00",
        duration: "1h 15m",
        price: 180,
        departureDate: "10-09-2023",
        arrivalDate: "10-09-2023",
    },
    {
        from: "Los Angeles",
        to: "Hong Kong",
        airline: "Cathay Pacific",
        departureAirportCode: "LAX",
        arrivalAirportCode: "HKG",
        departureTime: "14:15",
        arrivalTime: "20:45",
        duration: "9h 30m",
        price: 820,
        departureDate: "10-09-2023",
        arrivalDate: "10-09-2023",
    },
    {
        from: "Istanbul",
        to: "Toronto",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "YYZ",
        departureTime: "09:45",
        arrivalTime: "16:15",
        duration: "10h 30m",
        price: 700,
        departureDate: "11-09-2023",
        arrivalDate: "11-09-2023",
    },
    {
        from: "New York",
        to: "Paris",
        airline: "Air France",
        departureAirportCode: "JFK",
        arrivalAirportCode: "CDG",
        departureTime: "10:30",
        arrivalTime: "14:45",
        duration: "7h 15m",
        price: 580,
        departureDate: "11-09-2023",
        arrivalDate: "11-09-2023",
    },
    {
        from: "London",
        to: "Mumbai",
        airline: "British Airways",
        departureAirportCode: "LHR",
        arrivalAirportCode: "BOM",
        departureTime: "11:15",
        arrivalTime: "18:45",
        duration: "9h 30m",
        price: 750,
        departureDate: "11-09-2023",
        arrivalDate: "11-09-2023",
    },
    {
        from: "Tokyo",
        to: "Berlin",
        airline: "Lufthansa",
        departureAirportCode: "NRT",
        arrivalAirportCode: "TXL",
        departureTime: "12:00",
        arrivalTime: "17:30",
        duration: "8h 30m",
        price: 720,
        departureDate: "11-09-2023",
        arrivalDate: "11-09-2023",
    },
    {
        from: "Dubai",
        to: "Los Angeles",
        airline: "Emirates",
        departureAirportCode: "DXB",
        arrivalAirportCode: "LAX",
        departureTime: "13:00",
        arrivalTime: "19:30",
        duration: "17h 30m",
        price: 1000,
        departureDate: "11-09-2023",
        arrivalDate: "11-09-2023",
    },
    {
        from: "Hong Kong",
        to: "Istanbul",
        airline: "Turkish Airlines",
        departureAirportCode: "HKG",
        arrivalAirportCode: "IST",
        departureTime: "13:30",
        arrivalTime: "20:00",
        duration: "9h 30m",
        price: 780,
        departureDate: "11-09-2023",
        arrivalDate: "11-09-2023",
    },
    {
        from: "Istanbul",
        to: "Rome",
        airline: "Turkish Airlines",
        departureAirportCode: "IST",
        arrivalAirportCode: "FCO",
        departureTime: "09:15",
        arrivalTime: "12:30",
        duration: "3h 15m",
        price: 320,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "New York",
        to: "Toronto",
        airline: "Delta Air Lines",
        departureAirportCode: "JFK",
        arrivalAirportCode: "YYZ",
        departureTime: "10:45",
        arrivalTime: "17:15",
        duration: "11h 30m",
        price: 670,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "Paris",
        to: "Mumbai",
        airline: "Air France",
        departureAirportCode: "CDG",
        arrivalAirportCode: "BOM",
        departureTime: "11:30",
        arrivalTime: "19:00",
        duration: "9h 30m",
        price: 780,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "Sydney",
        to: "Berlin",
        airline: "Qantas Airways",
        departureAirportCode: "SYD",
        arrivalAirportCode: "TXL",
        departureTime: "12:15",
        arrivalTime: "18:45",
        duration: "9h 30m",
        price: 720,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
    {
        from: "Berlin",
        to: "Hong Kong",
        airline: "Lufthansa",
        departureAirportCode: "TXL",
        arrivalAirportCode: "HKG",
        departureTime: "13:45",
        arrivalTime: "21:15",
        duration: "10h 30m",
        price: 840,
        departureDate: "12-09-2023",
        arrivalDate: "12-09-2023",
    },
];


